[2024-06-02T10:43:16.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T10:43:16.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T10:43:16.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T10:43:16.871+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T10:43:17.011+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 03:00:00+00:00
[2024-06-02T10:43:17.019+0000] {standard_task_runner.py:63} INFO - Started process 1097 to run task
[2024-06-02T10:43:17.023+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T03:00:00+00:00', '--job-id', '867', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpa1r5d9jj']
[2024-06-02T10:43:17.026+0000] {standard_task_runner.py:91} INFO - Job 867: Subtask check_status
[2024-06-02T10:43:17.136+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T10:43:17.604+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T03:00:00+00:00'
[2024-06-02T10:43:17.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T10:43:17.648+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-02T10:43:17.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T10:43:17.709+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T03:00:00+00:00, execution_date=20240602T030000, start_date=20240602T104316, end_date=20240602T104317
[2024-06-02T10:43:17.761+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T10:43:17.788+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T10:43:17.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:42:41.981+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:42:42.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T11:42:42.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T11:42:42.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:42:43.243+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 03:00:00+00:00
[2024-06-02T11:42:43.251+0000] {standard_task_runner.py:63} INFO - Started process 2016 to run task
[2024-06-02T11:42:43.255+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T03:00:00+00:00', '--job-id', '866', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpqo0diz73']
[2024-06-02T11:42:43.258+0000] {standard_task_runner.py:91} INFO - Job 866: Subtask check_status
[2024-06-02T11:42:43.430+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:42:43.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T03:00:00+00:00'
[2024-06-02T11:42:43.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:42:43.798+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:42:43.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:42:43.890+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T03:00:00+00:00, execution_date=20240602T030000, start_date=20240602T114242, end_date=20240602T114243
[2024-06-02T11:42:43.993+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:42:44.052+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:42:44.057+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:43:11.342+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:43:11.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T12:43:11.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [queued]>
[2024-06-02T12:43:11.659+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:43:11.802+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 03:00:00+00:00
[2024-06-02T12:43:11.809+0000] {standard_task_runner.py:63} INFO - Started process 3605 to run task
[2024-06-02T12:43:11.813+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T03:00:00+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp7q7uz05j']
[2024-06-02T12:43:11.820+0000] {standard_task_runner.py:91} INFO - Job 918: Subtask check_status
[2024-06-02T12:43:12.241+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T03:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:43:12.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T03:00:00+00:00'
[2024-06-02T12:43:12.700+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:43:12.806+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:43:12.809+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:43:12.850+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T03:00:00+00:00, execution_date=20240602T030000, start_date=20240602T124311, end_date=20240602T124312
[2024-06-02T12:43:12.964+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 918 for task check_status (Request returned non-success status: failed; 3605)
[2024-06-02T12:43:12.999+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:43:13.200+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:43:13.202+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
