[2024-06-01T21:29:42.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:29:42.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-01T21:29:42.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-01T21:29:42.227+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:29:42.400+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 14:30:00+00:00
[2024-06-01T21:29:42.408+0000] {standard_task_runner.py:63} INFO - Started process 769 to run task
[2024-06-01T21:29:42.412+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T14:30:00+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpf__f4lnl']
[2024-06-01T21:29:42.420+0000] {standard_task_runner.py:91} INFO - Job 816: Subtask check_status
[2024-06-01T21:29:42.523+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:29:42.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T14:30:00+00:00'
[2024-06-01T21:29:42.742+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:29:42.774+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:29:42.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:29:42.846+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T14:30:00+00:00, execution_date=20240601T143000, start_date=20240601T212942, end_date=20240601T212942
[2024-06-01T21:29:42.915+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:29:42.947+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:29:42.950+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:34:05.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:34:05.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T11:34:05.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T11:34:05.623+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:34:05.759+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 14:30:00+00:00
[2024-06-02T11:34:05.765+0000] {standard_task_runner.py:63} INFO - Started process 1741 to run task
[2024-06-02T11:34:05.768+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T14:30:00+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpgs4bscxw']
[2024-06-02T11:34:05.770+0000] {standard_task_runner.py:91} INFO - Job 816: Subtask check_status
[2024-06-02T11:34:05.868+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:34:06.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T14:30:00+00:00'
[2024-06-02T11:34:06.105+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:34:06.297+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:34:06.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:34:06.415+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T14:30:00+00:00, execution_date=20240601T143000, start_date=20240602T113405, end_date=20240602T113406
[2024-06-02T11:34:06.588+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:34:06.616+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:34:06.618+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:05:53.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:05:53.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T12:05:53.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T12:05:53.548+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:05:53.738+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 14:30:00+00:00
[2024-06-02T12:05:53.745+0000] {standard_task_runner.py:63} INFO - Started process 2615 to run task
[2024-06-02T12:05:53.749+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T14:30:00+00:00', '--job-id', '834', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpbgkwpwne']
[2024-06-02T12:05:53.752+0000] {standard_task_runner.py:91} INFO - Job 834: Subtask check_status
[2024-06-02T12:05:53.846+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:05:54.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T14:30:00+00:00'
[2024-06-02T12:05:54.085+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:05:54.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:05:54.136+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:05:54.166+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T14:30:00+00:00, execution_date=20240601T143000, start_date=20240602T120553, end_date=20240602T120554
[2024-06-02T12:05:54.252+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 834 for task check_status (Check send status failed: {'status': 'failed'}; 2615)
[2024-06-02T12:05:54.282+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:05:54.309+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:05:54.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:25:48.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:25:48.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T12:25:48.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [queued]>
[2024-06-02T12:25:48.871+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:25:48.918+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 14:30:00+00:00
[2024-06-02T12:25:48.923+0000] {standard_task_runner.py:63} INFO - Started process 3155 to run task
[2024-06-02T12:25:48.928+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T14:30:00+00:00', '--job-id', '836', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp36_r6lwt']
[2024-06-02T12:25:48.930+0000] {standard_task_runner.py:91} INFO - Job 836: Subtask check_status
[2024-06-02T12:25:49.174+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T14:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:25:49.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T14:30:00+00:00'
[2024-06-02T12:25:49.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:25:49.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:25:49.390+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:25:49.411+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T14:30:00+00:00, execution_date=20240601T143000, start_date=20240602T122548, end_date=20240602T122549
[2024-06-02T12:25:49.462+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 836 for task check_status (Check send status failed: {'status': 'failed'}; 3155)
[2024-06-02T12:25:49.502+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:25:49.627+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:25:49.630+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
