[2024-05-30T08:34:01.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T08:34:01.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T03:10:00+00:00 [queued]>
[2024-05-30T08:34:01.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T03:10:00+00:00 [queued]>
[2024-05-30T08:34:01.232+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-30T08:34:01.392+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): monitor_flask_logs> on 2024-05-28 03:10:00+00:00
[2024-05-30T08:34:01.398+0000] {standard_task_runner.py:63} INFO - Started process 148 to run task
[2024-05-30T08:34:01.402+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'flask_monitoring', 'monitor_flask_logs', 'scheduled__2024-05-28T03:10:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/flask_monitoring.py', '--cfg-path', '/tmp/tmpobize2um']
[2024-05-30T08:34:01.405+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask monitor_flask_logs
[2024-05-30T08:34:01.549+0000] {task_command.py:426} INFO - Running <TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T03:10:00+00:00 [running]> on host f708138922bb
[2024-05-30T08:34:01.793+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flask_monitoring' AIRFLOW_CTX_TASK_ID='monitor_flask_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T03:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T03:10:00+00:00'
[2024-05-30T08:34:01.795+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T08:34:01.827+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T08:34:01.830+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker logs 93adf74dff35']
[2024-05-30T08:34:01.846+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T08:34:01.888+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-30T08:34:01.890+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T08:34:01.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T08:34:01.917+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T08:34:01.929+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flask_monitoring, task_id=monitor_flask_logs, run_id=scheduled__2024-05-28T03:10:00+00:00, execution_date=20240528T031000, start_date=20240530T083401, end_date=20240530T083401
[2024-05-30T08:34:01.988+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 227 for task monitor_flask_logs (Bash command failed. The command returned a non-zero exit code 1.; 148)
[2024-05-30T08:34:02.019+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T08:34:02.090+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T08:34:02.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
