[2024-06-02T12:55:37.987+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:55:38.050+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T08:00:00+00:00 [queued]>
[2024-06-02T12:55:38.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T08:00:00+00:00 [queued]>
[2024-06-02T12:55:38.074+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:55:38.130+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 08:00:00+00:00
[2024-06-02T12:55:38.141+0000] {standard_task_runner.py:63} INFO - Started process 3929 to run task
[2024-06-02T12:55:38.141+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T08:00:00+00:00', '--job-id', '977', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp273o8883']
[2024-06-02T12:55:38.154+0000] {standard_task_runner.py:91} INFO - Job 977: Subtask check_status
[2024-06-02T12:55:38.529+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T08:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:55:38.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T08:00:00+00:00'
[2024-06-02T12:55:38.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:55:38.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:55:38.723+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:55:38.748+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T08:00:00+00:00, execution_date=20240602T080000, start_date=20240602T125538, end_date=20240602T125538
[2024-06-02T12:55:38.801+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 977 for task check_status (Request returned non-success status: failed; 3929)
[2024-06-02T12:55:38.850+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:55:39.014+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:55:39.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
