[2024-05-30T08:58:50.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T08:58:50.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-29T02:05:00+00:00 [queued]>
[2024-05-30T08:58:50.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-29T02:05:00+00:00 [queued]>
[2024-05-30T08:58:50.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-30T08:58:50.902+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): monitor_flask_logs> on 2024-05-29 02:05:00+00:00
[2024-05-30T08:58:50.917+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'flask_monitoring', 'monitor_flask_logs', 'scheduled__2024-05-29T02:05:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/flask_monitoring.py', '--cfg-path', '/tmp/tmprbronjkh']
[2024-05-30T08:58:50.922+0000] {standard_task_runner.py:91} INFO - Job 310: Subtask monitor_flask_logs
[2024-05-30T08:58:50.911+0000] {standard_task_runner.py:63} INFO - Started process 997 to run task
[2024-05-30T08:58:53.473+0000] {task_command.py:426} INFO - Running <TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-29T02:05:00+00:00 [running]> on host f708138922bb
[2024-05-30T08:58:54.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flask_monitoring' AIRFLOW_CTX_TASK_ID='monitor_flask_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T02:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-29T02:05:00+00:00'
[2024-05-30T08:58:54.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T08:58:54.556+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T08:58:54.558+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker logs 93adf74dff35']
[2024-05-30T08:58:54.582+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T08:58:54.661+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-30T08:58:54.665+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T08:58:54.677+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T08:58:54.723+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T08:58:54.752+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=flask_monitoring, task_id=monitor_flask_logs, run_id=scheduled__2024-05-29T02:05:00+00:00, execution_date=20240529T020500, start_date=20240530T085850, end_date=20240530T085854
[2024-05-30T08:58:54.867+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 310 for task monitor_flask_logs (Bash command failed. The command returned a non-zero exit code 1.; 997)
[2024-05-30T08:58:54.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T08:58:54.981+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T08:58:54.994+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
