[2024-06-01T21:20:52.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:20:52.847+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-01T21:20:52.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-01T21:20:52.869+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:20:53.024+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 01:30:00+00:00
[2024-06-01T21:20:53.030+0000] {standard_task_runner.py:63} INFO - Started process 482 to run task
[2024-06-01T21:20:53.034+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T01:30:00+00:00', '--job-id', '764', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpiptul02k']
[2024-06-01T21:20:53.036+0000] {standard_task_runner.py:91} INFO - Job 764: Subtask check_status
[2024-06-01T21:20:53.164+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:20:53.378+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T01:30:00+00:00'
[2024-06-01T21:20:53.379+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:20:53.413+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:20:53.414+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:20:53.483+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T01:30:00+00:00, execution_date=20240601T013000, start_date=20240601T212052, end_date=20240601T212053
[2024-06-01T21:20:53.568+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:20:53.600+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:20:53.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:23:29.832+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:23:29.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T11:23:29.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T11:23:29.912+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:23:30.147+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 01:30:00+00:00
[2024-06-02T11:23:30.153+0000] {standard_task_runner.py:63} INFO - Started process 1453 to run task
[2024-06-02T11:23:30.156+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T01:30:00+00:00', '--job-id', '764', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpqte1lnir']
[2024-06-02T11:23:30.162+0000] {standard_task_runner.py:91} INFO - Job 764: Subtask check_status
[2024-06-02T11:23:30.298+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:23:30.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T01:30:00+00:00'
[2024-06-02T11:23:30.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:23:30.586+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:23:30.589+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:23:30.661+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T01:30:00+00:00, execution_date=20240601T013000, start_date=20240602T112329, end_date=20240602T112330
[2024-06-02T11:23:30.737+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:23:30.762+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:23:30.764+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:52:17.397+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:52:17.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T11:52:17.489+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T11:52:17.490+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:52:17.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 01:30:00+00:00
[2024-06-02T11:52:17.566+0000] {standard_task_runner.py:63} INFO - Started process 2239 to run task
[2024-06-02T11:52:17.569+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T01:30:00+00:00', '--job-id', '765', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpf99hkyiu']
[2024-06-02T11:52:17.571+0000] {standard_task_runner.py:91} INFO - Job 765: Subtask check_status
[2024-06-02T11:52:17.815+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:52:17.994+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T01:30:00+00:00'
[2024-06-02T11:52:17.995+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:52:18.025+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:52:18.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 26, in check_send_status
    raise ValueError(f"Task failed with status: {status}")
ValueError: Task failed with status: failed
[2024-06-02T11:52:18.050+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T01:30:00+00:00, execution_date=20240601T013000, start_date=20240602T115217, end_date=20240602T115218
[2024-06-02T11:52:18.102+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 765 for task check_status (Task failed with status: failed; 2239)
[2024-06-02T11:52:18.143+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T11:52:18.273+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:52:18.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:13:42.812+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:13:42.859+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T12:13:42.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [queued]>
[2024-06-02T12:13:42.882+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:13:42.951+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 01:30:00+00:00
[2024-06-02T12:13:42.958+0000] {standard_task_runner.py:63} INFO - Started process 2762 to run task
[2024-06-02T12:13:42.961+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T01:30:00+00:00', '--job-id', '765', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpe0hk_z22']
[2024-06-02T12:13:42.964+0000] {standard_task_runner.py:91} INFO - Job 765: Subtask check_status
[2024-06-02T12:13:43.211+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T01:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:13:43.435+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T01:30:00+00:00'
[2024-06-02T12:13:43.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:13:43.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:13:43.461+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:13:43.486+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T01:30:00+00:00, execution_date=20240601T013000, start_date=20240602T121342, end_date=20240602T121343
[2024-06-02T12:13:43.552+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 765 for task check_status (Check send status failed: {'status': 'failed'}; 2762)
[2024-06-02T12:13:43.581+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:13:43.734+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:13:43.736+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
