[2024-06-01T21:28:32.618+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:28:32.679+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-01T21:28:32.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-01T21:28:32.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:28:32.864+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 12:30:00+00:00
[2024-06-01T21:28:32.870+0000] {standard_task_runner.py:63} INFO - Started process 725 to run task
[2024-06-01T21:28:32.873+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T12:30:00+00:00', '--job-id', '808', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmprfv0w_2p']
[2024-06-01T21:28:32.875+0000] {standard_task_runner.py:91} INFO - Job 808: Subtask check_status
[2024-06-01T21:28:33.002+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:28:33.199+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T12:30:00+00:00'
[2024-06-01T21:28:33.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:28:33.234+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:28:33.235+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:28:33.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T12:30:00+00:00, execution_date=20240601T123000, start_date=20240601T212832, end_date=20240601T212833
[2024-06-01T21:28:33.371+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:28:33.397+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:28:33.399+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:32:44.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:32:44.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T11:32:44.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T11:32:44.784+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:32:44.934+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 12:30:00+00:00
[2024-06-02T11:32:44.940+0000] {standard_task_runner.py:63} INFO - Started process 1697 to run task
[2024-06-02T11:32:44.944+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T12:30:00+00:00', '--job-id', '808', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpymvz9f35']
[2024-06-02T11:32:44.946+0000] {standard_task_runner.py:91} INFO - Job 808: Subtask check_status
[2024-06-02T11:32:45.063+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:32:45.248+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T12:30:00+00:00'
[2024-06-02T11:32:45.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:32:45.294+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:32:45.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:32:45.371+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T12:30:00+00:00, execution_date=20240601T123000, start_date=20240602T113244, end_date=20240602T113245
[2024-06-02T11:32:45.478+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:32:45.526+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:32:45.528+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:04:33.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:04:33.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T12:04:33.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T12:04:33.420+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:04:33.626+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 12:30:00+00:00
[2024-06-02T12:04:33.631+0000] {standard_task_runner.py:63} INFO - Started process 2571 to run task
[2024-06-02T12:04:33.635+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T12:30:00+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp3nl5ratq']
[2024-06-02T12:04:33.637+0000] {standard_task_runner.py:91} INFO - Job 826: Subtask check_status
[2024-06-02T12:04:33.741+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:04:33.953+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T12:30:00+00:00'
[2024-06-02T12:04:33.954+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:04:33.981+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:04:33.982+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:04:34.007+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T12:30:00+00:00, execution_date=20240601T123000, start_date=20240602T120433, end_date=20240602T120434
[2024-06-02T12:04:34.058+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 826 for task check_status (Check send status failed: {'status': 'failed'}; 2571)
[2024-06-02T12:04:34.088+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:04:34.123+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:04:34.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:24:12.387+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:24:12.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T12:24:12.471+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [queued]>
[2024-06-02T12:24:12.471+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:24:12.552+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 12:30:00+00:00
[2024-06-02T12:24:12.558+0000] {standard_task_runner.py:63} INFO - Started process 3100 to run task
[2024-06-02T12:24:12.561+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T12:30:00+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpf968oxfm']
[2024-06-02T12:24:12.563+0000] {standard_task_runner.py:91} INFO - Job 826: Subtask check_status
[2024-06-02T12:24:13.144+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T12:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:24:13.574+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T12:30:00+00:00'
[2024-06-02T12:24:13.575+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:24:13.601+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:24:13.603+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:24:13.629+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T12:30:00+00:00, execution_date=20240601T123000, start_date=20240602T122412, end_date=20240602T122413
[2024-06-02T12:24:13.702+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 826 for task check_status (Check send status failed: {'status': 'failed'}; 3100)
[2024-06-02T12:24:13.738+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:24:13.894+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:24:13.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
