[2024-06-01T21:31:24.347+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:31:24.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-01T21:31:24.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-01T21:31:24.441+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:31:24.616+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 17:00:00+00:00
[2024-06-01T21:31:24.622+0000] {standard_task_runner.py:63} INFO - Started process 829 to run task
[2024-06-01T21:31:24.625+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T17:00:00+00:00', '--job-id', '827', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpokwre94l']
[2024-06-01T21:31:24.628+0000] {standard_task_runner.py:91} INFO - Job 827: Subtask check_status
[2024-06-01T21:31:24.747+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:31:25.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T17:00:00+00:00'
[2024-06-01T21:31:25.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:31:25.156+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:31:25.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:31:25.234+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T17:00:00+00:00, execution_date=20240601T170000, start_date=20240601T213124, end_date=20240601T213125
[2024-06-01T21:31:25.321+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:31:25.379+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:31:25.384+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:35:52.023+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:35:52.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-02T11:35:52.088+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-02T11:35:52.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:35:52.230+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 17:00:00+00:00
[2024-06-02T11:35:52.236+0000] {standard_task_runner.py:63} INFO - Started process 1801 to run task
[2024-06-02T11:35:52.240+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T17:00:00+00:00', '--job-id', '827', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmppgr7kfq9']
[2024-06-02T11:35:52.242+0000] {standard_task_runner.py:91} INFO - Job 827: Subtask check_status
[2024-06-02T11:35:52.340+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:35:52.539+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T17:00:00+00:00'
[2024-06-02T11:35:52.541+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:35:52.576+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:35:52.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:35:52.652+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T17:00:00+00:00, execution_date=20240601T170000, start_date=20240602T113552, end_date=20240602T113552
[2024-06-02T11:35:52.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:35:52.759+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:35:52.762+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:29:13.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:29:13.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-02T12:29:13.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [queued]>
[2024-06-02T12:29:13.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:29:13.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 17:00:00+00:00
[2024-06-02T12:29:13.873+0000] {standard_task_runner.py:63} INFO - Started process 3252 to run task
[2024-06-02T12:29:13.877+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T17:00:00+00:00', '--job-id', '854', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp8n5wt226']
[2024-06-02T12:29:13.879+0000] {standard_task_runner.py:91} INFO - Job 854: Subtask check_status
[2024-06-02T12:29:14.143+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T17:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:29:14.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T17:00:00+00:00'
[2024-06-02T12:29:14.330+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:29:14.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:29:14.354+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:29:14.373+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T17:00:00+00:00, execution_date=20240601T170000, start_date=20240602T122913, end_date=20240602T122914
[2024-06-02T12:29:14.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 854 for task check_status (Request returned non-success status: failed; 3252)
[2024-06-02T12:29:14.452+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:29:14.648+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:29:14.651+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
