[2024-05-29T17:19:14.155+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T17:19:14.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T02:00:00+00:00 [queued]>
[2024-05-29T17:19:14.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T02:00:00+00:00 [queued]>
[2024-05-29T17:19:14.280+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-29T17:19:14.343+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): monitor_flask_logs> on 2024-05-28 02:00:00+00:00
[2024-05-29T17:19:14.351+0000] {standard_task_runner.py:63} INFO - Started process 2262 to run task
[2024-05-29T17:19:14.355+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'flask_monitoring', 'monitor_flask_logs', 'scheduled__2024-05-28T02:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/flask_monitoring.py', '--cfg-path', '/tmp/tmpfd3fdtsp']
[2024-05-29T17:19:14.358+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask monitor_flask_logs
[2024-05-29T17:19:14.537+0000] {task_command.py:426} INFO - Running <TaskInstance: flask_monitoring.monitor_flask_logs scheduled__2024-05-28T02:00:00+00:00 [running]> on host f708138922bb
[2024-05-29T17:19:14.729+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flask_monitoring' AIRFLOW_CTX_TASK_ID='monitor_flask_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T02:00:00+00:00'
[2024-05-29T17:19:14.730+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T17:19:14.746+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-29T17:19:14.747+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker logs 93adf74dff35']
[2024-05-29T17:19:14.757+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T17:19:14.778+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-29T17:19:14.780+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-29T17:19:14.781+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T17:19:14.804+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-29T17:19:14.811+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=flask_monitoring, task_id=monitor_flask_logs, run_id=scheduled__2024-05-28T02:00:00+00:00, execution_date=20240528T020000, start_date=20240529T171914, end_date=20240529T171914
[2024-05-29T17:19:14.862+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task monitor_flask_logs (Bash command failed. The command returned a non-zero exit code 1.; 2262)
[2024-05-29T17:19:14.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T17:19:15.006+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T17:19:15.012+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
