[2024-06-02T12:48:26.609+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:48:26.691+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:30:00+00:00 [queued]>
[2024-06-02T12:48:26.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:30:00+00:00 [queued]>
[2024-06-02T12:48:26.800+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:48:27.097+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 02:30:00+00:00
[2024-06-02T12:48:27.111+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T02:30:00+00:00', '--job-id', '943', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpkkwlnqom']
[2024-06-02T12:48:27.106+0000] {standard_task_runner.py:63} INFO - Started process 3741 to run task
[2024-06-02T12:48:27.118+0000] {standard_task_runner.py:91} INFO - Job 943: Subtask check_status
[2024-06-02T12:48:27.597+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:48:27.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T02:30:00+00:00'
[2024-06-02T12:48:27.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:48:28.021+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:48:28.024+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:48:28.054+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T02:30:00+00:00, execution_date=20240602T023000, start_date=20240602T124826, end_date=20240602T124828
[2024-06-02T12:48:28.158+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 943 for task check_status (Request returned non-success status: failed; 3741)
[2024-06-02T12:48:28.179+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:48:28.363+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:48:28.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
