[2024-06-01T21:32:35.136+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:32:35.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-01T21:32:35.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-01T21:32:35.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:32:35.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:00:00+00:00
[2024-06-01T21:32:35.366+0000] {standard_task_runner.py:63} INFO - Started process 873 to run task
[2024-06-01T21:32:35.369+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:00:00+00:00', '--job-id', '835', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpi2sj2n92']
[2024-06-01T21:32:35.371+0000] {standard_task_runner.py:91} INFO - Job 835: Subtask check_status
[2024-06-01T21:32:35.486+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:32:35.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:00:00+00:00'
[2024-06-01T21:32:35.707+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:32:35.736+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:32:35.737+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:32:35.800+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:00:00+00:00, execution_date=20240601T190000, start_date=20240601T213235, end_date=20240601T213235
[2024-06-01T21:32:35.904+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:32:35.957+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:32:35.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:37:03.581+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:37:03.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-02T11:37:03.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-02T11:37:03.817+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:37:04.196+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:00:00+00:00
[2024-06-02T11:37:04.205+0000] {standard_task_runner.py:63} INFO - Started process 1845 to run task
[2024-06-02T11:37:04.209+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:00:00+00:00', '--job-id', '835', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpewgmdnvw']
[2024-06-02T11:37:04.212+0000] {standard_task_runner.py:91} INFO - Job 835: Subtask check_status
[2024-06-02T11:37:04.358+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:37:05.537+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:00:00+00:00'
[2024-06-02T11:37:05.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:37:05.596+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:37:05.597+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:37:05.662+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:00:00+00:00, execution_date=20240601T190000, start_date=20240602T113703, end_date=20240602T113705
[2024-06-02T11:37:05.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:37:05.783+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:37:05.786+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:31:37.344+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:31:37.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-02T12:31:37.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [queued]>
[2024-06-02T12:31:37.426+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:31:37.478+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:00:00+00:00
[2024-06-02T12:31:37.484+0000] {standard_task_runner.py:63} INFO - Started process 3325 to run task
[2024-06-02T12:31:37.487+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:00:00+00:00', '--job-id', '867', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpvmky8xjv']
[2024-06-02T12:31:37.489+0000] {standard_task_runner.py:91} INFO - Job 867: Subtask check_status
[2024-06-02T12:31:37.723+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:31:37.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:00:00+00:00'
[2024-06-02T12:31:37.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:31:38.003+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:31:38.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:31:38.034+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:00:00+00:00, execution_date=20240601T190000, start_date=20240602T123137, end_date=20240602T123138
[2024-06-02T12:31:38.111+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 867 for task check_status (Request returned non-success status: failed; 3325)
[2024-06-02T12:31:38.145+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:31:38.512+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:31:38.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
