[2024-06-01T21:32:53.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T21:32:53.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-01T21:32:53.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-01T21:32:53.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-01T21:32:53.734+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:30:00+00:00
[2024-06-01T21:32:53.740+0000] {standard_task_runner.py:63} INFO - Started process 884 to run task
[2024-06-01T21:32:53.744+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:30:00+00:00', '--job-id', '837', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpnzmfjjt0']
[2024-06-01T21:32:53.746+0000] {standard_task_runner.py:91} INFO - Job 837: Subtask check_status
[2024-06-01T21:32:53.853+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-01T21:32:54.084+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:30:00+00:00'
[2024-06-01T21:32:54.085+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T21:32:54.115+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-01T21:32:54.117+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T21:32:54.184+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:30:00+00:00, execution_date=20240601T193000, start_date=20240601T213253, end_date=20240601T213254
[2024-06-01T21:32:54.278+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T21:32:54.314+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T21:32:54.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:37:27.103+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:37:27.148+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-02T11:37:27.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-02T11:37:27.186+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:37:28.679+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:30:00+00:00
[2024-06-02T11:37:28.688+0000] {standard_task_runner.py:63} INFO - Started process 1856 to run task
[2024-06-02T11:37:28.692+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:30:00+00:00', '--job-id', '837', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpnpx8m1qc']
[2024-06-02T11:37:28.695+0000] {standard_task_runner.py:91} INFO - Job 837: Subtask check_status
[2024-06-02T11:37:28.998+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:37:29.774+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:30:00+00:00'
[2024-06-02T11:37:29.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:37:29.824+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:37:29.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:37:29.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:30:00+00:00, execution_date=20240601T193000, start_date=20240602T113727, end_date=20240602T113729
[2024-06-02T11:37:29.957+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:37:29.988+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:37:29.990+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:33:01.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:33:01.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-02T12:33:02.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [queued]>
[2024-06-02T12:33:02.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:33:02.164+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 19:30:00+00:00
[2024-06-02T12:33:02.170+0000] {standard_task_runner.py:63} INFO - Started process 3347 to run task
[2024-06-02T12:33:02.173+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T19:30:00+00:00', '--job-id', '871', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp0hljdhlf']
[2024-06-02T12:33:02.175+0000] {standard_task_runner.py:91} INFO - Job 871: Subtask check_status
[2024-06-02T12:33:02.683+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T19:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:33:03.097+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T19:30:00+00:00'
[2024-06-02T12:33:03.098+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:33:03.140+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:33:03.144+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:33:03.185+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T19:30:00+00:00, execution_date=20240601T193000, start_date=20240602T123301, end_date=20240602T123303
[2024-06-02T12:33:03.267+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 871 for task check_status (Request returned non-success status: failed; 3347)
[2024-06-02T12:33:03.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:33:03.582+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:33:03.589+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
