[2024-06-02T10:42:29.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T10:42:29.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T10:42:29.130+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T10:42:29.132+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T10:42:29.313+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 02:00:00+00:00
[2024-06-02T10:42:29.320+0000] {standard_task_runner.py:63} INFO - Started process 1070 to run task
[2024-06-02T10:42:29.325+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T02:00:00+00:00', '--job-id', '862', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp8yb2ikvo']
[2024-06-02T10:42:29.332+0000] {standard_task_runner.py:91} INFO - Job 862: Subtask check_status
[2024-06-02T10:42:29.635+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T10:42:29.885+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T02:00:00+00:00'
[2024-06-02T10:42:29.887+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T10:42:29.968+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-02T10:42:29.971+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T10:42:30.178+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T02:00:00+00:00, execution_date=20240602T020000, start_date=20240602T104229, end_date=20240602T104230
[2024-06-02T10:42:30.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T10:42:30.300+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T10:42:30.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T11:42:13.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:42:13.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T11:42:13.475+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T11:42:13.476+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T11:42:13.612+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 02:00:00+00:00
[2024-06-02T11:42:13.618+0000] {standard_task_runner.py:63} INFO - Started process 1999 to run task
[2024-06-02T11:42:13.621+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T02:00:00+00:00', '--job-id', '863', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmprsztun4d']
[2024-06-02T11:42:13.623+0000] {standard_task_runner.py:91} INFO - Job 863: Subtask check_status
[2024-06-02T11:42:13.917+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:42:14.356+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T02:00:00+00:00'
[2024-06-02T11:42:14.359+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:42:14.407+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'failed'}
[2024-06-02T11:42:14.409+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:42:14.488+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T02:00:00+00:00, execution_date=20240602T020000, start_date=20240602T114213, end_date=20240602T114214
[2024-06-02T11:42:14.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:42:14.637+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:42:14.639+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:42:06.463+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:42:06.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T12:42:06.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [queued]>
[2024-06-02T12:42:06.543+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-02T12:42:06.643+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-02 02:00:00+00:00
[2024-06-02T12:42:06.650+0000] {standard_task_runner.py:63} INFO - Started process 3577 to run task
[2024-06-02T12:42:06.653+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-02T02:00:00+00:00', '--job-id', '913', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpqn0w8eis']
[2024-06-02T12:42:06.656+0000] {standard_task_runner.py:91} INFO - Job 913: Subtask check_status
[2024-06-02T12:42:06.965+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-02T02:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:42:07.234+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T02:00:00+00:00'
[2024-06-02T12:42:07.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:42:07.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:42:07.290+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Request returned non-success status: {response_json.get('status')}")
ValueError: Request returned non-success status: failed
[2024-06-02T12:42:07.347+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-02T02:00:00+00:00, execution_date=20240602T020000, start_date=20240602T124206, end_date=20240602T124207
[2024-06-02T12:42:07.492+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 913 for task check_status (Request returned non-success status: failed; 3577)
[2024-06-02T12:42:07.522+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:42:08.024+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:42:08.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
